### ISSUE TITLE
Change to replace all

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/strmat#21]
Currently the libray replaces only the first occurence of the placeholder.

But we need it to support replace all the occurences.

For this there should be a chane at this line

https://github.com/arshadkazmi42/strmat/blob/master/index.js#L15

To use regex with `g` to replace all.

**Comment by sivasuriyankumarasamy** [comment]
@arshadkazmi42 Can you assign this to me?

**Comment by arshadkazmi42** [comment]
Assigned
